CORPUS_PATH = 'D:\\usr\\gwm\\c_w\\lib.rus.ec'
ALL_CLASSES = ['sf', 'det', 'prose', 'love', 'adv', 'child', 'antique', 'sci', 'comp', 'ref', 'nonf', 'religi', 'humor', 'home', 'poetry', 'dramaturgy', 'periodic', 'other', 'russian_cont']
MAX_NUMBER = 100
PREDICTION_DATA = {'X_train': [], 'y_train': [], 'X_test': [], 'y_test': []}
X_TRAIN_PATH = 'D:\\usr\\gwm\\pyprojects\\automatic_detection_of_russian_text_genre\\train_samples\\w2v_train'
ALL_DATA_PATH = 'D:\\usr\\gwm\\pyprojects\\automatic_detection_of_russian_text_genre\\train_data\\small_balanced_dataset_dictionary.pkl'
X_TEST_PATH = 'D:\\usr\\gwm\\pyprojects\\automatic_detection_of_russian_text_genre\\train_samples\\w2v_test'
RUSVECTORES_PATH = 'D:\\usr\\gwm\\pyprojects\\automatic_detection_of_russian_text_genre\\models\\ruwikiruscorpora_0_300_20.bin'
SEQUENCE_LENGTH = 40000
WORD2VEC_DIM = 300